apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpserver-deployment
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 100%
  selector:
    matchLabels:
      app: httpserver
  template:
    metadata:
      labels:
        app: httpserver
    spec:
      restartPolicy: Always # Always, OnFailure, Never
      containers:
        - name: http-container
          image: blux2/hello-server:1.8
          imagePullPolicy: IfNotPresent # Always, IfNotPresent, Never
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 10m
              memory: 1Gi
            limits:
              cpu: 10m
              memory: 1Gi
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: 8080
          #   initialDelaySeconds: 5
          #   periodSeconds: 5
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: 8080
          #   initialDelaySeconds: 10
          #   periodSeconds: 5
