apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 10
  strategy: # storategyを指定していない場合のデフォルトは、RollingUpdate 25% max unavailable, 25% max surge となる.
    type: Recreate    # 既存のpodを削除してから、再作成する。 (=ダウンタイムあり。)
  selector:
    matchLabels:
      app: nginx #templateのlabelsと一致している必要がある。
  template:
    metadata:
      labels:
        app: nginx
    spec:
      restartPolicy: Always # Always, OnFailure, Never
      containers:
        - name: nginx
          image: nginx:1.25.3
          imagePullPolicy: IfNotPresent # Always, IfNotPresent, Never
          ports:
            - containerPort: 8080
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 10"]
