apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpserve-deployemnt
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpserve
  template:
    metadata:
      labels:
        app: httpserve
    spec:
      restartPolicy: Always # Always, OnFailure, Never
      containers:
        - name: http-container
          image: blux2/hello-server:1.6
          imagePullPolicy: IfNotPresent # Always, IfNotPresent, Never
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
        - name: busybox
          image: busybox:1.36.1
          command:
          - sleep
          - "9999"