apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpserver-deployment
spec:
  replicas: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 100%
  selector:
    matchLabels:
      app: httpserver
  template:
    metadata:
      labels:
        app: httpserver
    spec:
      containers:
        - name: http-container
          image: blux2/delayfailserver:1.1
          ports:
            - containerPort: 8080
          ## readinessProbe:　
          ## -> ヘルスチェックが成功するまではserviceに含めない。=トラフィックを受けない。
          ## -> ヘルスチェックに失敗してもpodは生存しているので、状況把握に監視が欲しい。
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5 # probeを実行するまでに5秒待つ。
            periodSeconds: 5 # probeが5秒間隔で実行される。
            timeoutSeconds: 10 # タイムアウト時間
            successThreshold: 3 # 3回probeクリアで成功とする。
            failureThreshold: 3 # 3回probe失敗で失敗。
