apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25% # podの置き換え時に、podを一度に削除する割合  (ex: 4個podがあったら、一回に削除するpodは1つだけ)
      maxSurge: 100% # podの置き換え時に、podを一度に作成する割合　(ex: replicas:10 の場合は、一度に10個全てを作成する)
  replicas: 10
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      restartPolicy: Always # Always, OnFailure, Never
      containers:
        - name: nginx
          image: nginx:1.25.3
          imagePullPolicy: IfNotPresent # Always, IfNotPresent, Never
          ports:
            - containerPort: 80
          volumeMounts:
          - name: nginx-volume
            mountPath: /etc/config
          lifecycle:
            postStart:
              exec:
                command: ["/bin/bash", "-c", "echo start pod"]
      volumes:
      - name: nginx-volume
        secret:
          secretName: nginx-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: nginx-secret
data:
  server.key: ZU05a3UzZWNDcFVMOXpQb0lJdUcycHRaWkM1Q3U0WkNRWFJ5bWxIYWpZdlp5ZmZwTTYK