apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 100%
  replicas: 10
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      restartPolicy: Always # Always, OnFailure, Never
      containers:
        - name: name
          image: nginx:1.25.3
          imagePullPolicy: IfNotPresent # Always, IfNotPresent, Never
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: nginx-configmap
                  key: PORT
            - name: HOST
              valueFrom:
                configMapKeyRef:
                  name: nginx-configmap
                  key: HOST
          lifecycle:
            postStart:
              exec:
                command: ["/bin/bash", "-c", "echo start pod"]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  PORT: "80"
  HOST: "localhost"
