apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-date
spec:
  schedule: "*/2 * * * *"           # 2分ごと
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: date
              image: ubuntu:22.04
              command:
                - date
          restartPolicy: OnFailure
